#Lives plugin config file (version 2)

generalOptions:
  itemName: Live        #Changes the name of the live item
  resetLives: 3         #Changes the default amount of lives for /l reset
  onJoinLives: 3        #Changes how much lives a player has when joining for the first time
  defStarted: true      #If lives counting should be on when plugins starts
  alwaysExtract: false  #If player can extract lives when lives counting is off

livesManagement:
  autoSave: true        #If lives should be saved automatically to file
  saveInterval: 30      #How often autosave can run (in seconds!)
  autoLoad: true        #If lives should be loaded from file on plugin start

scoreboard:
  defShown: false       #If scoreboard should be shown when plugins starts
  type: TAB             #Type of scoreboard (supported: TAB, SIDE, UNDER_NAME)
  name: Lives           #Scoreboard name, only shown when scoreboard type is set to SIDE

penalty:
  type: GM3             #Penalty for loosing the last life (GM3, BAN, TEMPBAN)
  tempbanTime: 60       #Tempban time (in minutes!)
  banMessage: You lost your last life!

#If you change this variable, your config will be cleared!
configVersion: 2.2