#Lives plugin config file (version 2)

generalOptions:
  itemName: Life        #Changes the name of the life item
  item: GHAST_TEAR      #Changes what is the life item. "List" of options: https://github.com/Bukkit/Bukkit/blob/master/src/main/java/org/bukkit/Material.java
  onJoinLives: 3        #Changes how much lives a player has when joining for the first time
  defStarted: true      #If lives counting should be on when plugins starts
  alwaysExtract: false  #If player can extract lives when lives counting is off

livesManagement:
  autoSave: true        #If lives should be saved automatically to file
  saveInterval: 30      #How often autosave can run (in seconds!)
  autoLoad: true        #If lives should be loaded from file on plugin start

scoreboard:
  defShown: true        #If scoreboard should be shown when plugins starts
  type: TAB             #Type of scoreboard (TAB, SIDE, UNDER_NAME)
  name: Lives           #Scoreboard name, only shown when scoreboard type is set to SIDE

penalty:
  type: GM3             #Penalty for loosing the last life (GM3, BAN, TEMPBAN)
  tempbanTime: 60       #Tempban time (in minutes!)
  banMessage: You lost your last life!

reviving:
  allowed: false        #If player can revive dead playerss
  cost: 3               #Cost (in lives) of revival
  lives: 3              #Number of lives you get after reviving

#If you change this variable, your config will be cleared!
configVersion: 2.5
