name: Lives
version: 1.9.1
author: bewu
main: me.bewu.lives.Main
api-version: 1.13
commands:
  lives:
    description: Main command, to get help use /lives help
    aliases: [l]
  lives_admin:
    description: Admin command for lives plugin.
    aliases: [la]
permissions:
  lives.*:
    description: Gives you all plugin permissions
    default: op
  lives.set:
    description: Allows you to reset, set and add players lives.
    default: op
  lives.get:
    description: Allows you to see other peoples lives.
    default: true
  lives.give:
    description: Allows you to give you the live item.
    default: op
  lives.control:
    description: Allows you to turn counting lives on and off.
    default: op
  lives.save:
    description: Allows you to save/load lives to/from file.
    default: op
  lives.moveItem:
    description: Allows you to move item.
    default: op
  lives.scoreboard:
    description: Allows you to show/hide scoreboard
    default: op
  lives.revive:
    description: Allows you to revive people even if it's turned off.
    default: op
  lives.revive.admin:
    description: Allows you to revive people "for free"
    default: op
